// Generated by CoffeeScript 1.10.0
(function() {
  var ReplrEvents;

  ReplrEvents = (function() {
    function ReplrEvents() {}

    ReplrEvents.prototype.WORKER_RECEIVE = 'WORKER_RECEIVE';

    return ReplrEvents;

  })();

  module.exports = ReplrEvents;

}).call(this);
